//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWay.Skynet.Cloud.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UWay.Skynet.Cloud.Data.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} function {1} requires {2} arguments.
        /// </summary>
        internal static string ArgumentCountError {
            get {
                return ResourceManager.GetString("ArgumentCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerable must implement at least IEnumerable.
        /// </summary>
        internal static string ArgumentEnumerableInvalid {
            get {
                return ResourceManager.GetString("ArgumentEnumerableInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue label target must be void.
        /// </summary>
        internal static string ArgumentLabel {
            get {
                return ResourceManager.GetString("ArgumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deduce query provider from query.
        /// </summary>
        internal static string ArgumentQuery {
            get {
                return ResourceManager.GetString("ArgumentQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeMapping: The member &apos;{0}.{1}&apos; referenced in {2} for &apos;{3}&apos; is not mapped or does not exist.
        /// </summary>
        internal static string AttrbuteMappingError {
            get {
                return ResourceManager.GetString("AttrbuteMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test must be a boolean expression.
        /// </summary>
        internal static string BooleanExpression {
            get {
                return ResourceManager.GetString("BooleanExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type mapping for SqlType {0}.
        /// </summary>
        internal static string CastTypeInvalid {
            get {
                return ResourceManager.GetString("CastTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to undefined column.
        /// </summary>
        internal static string ColumnUndefine {
            get {
                return ResourceManager.GetString("ColumnUndefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        internal static string ConnectionStringConfigError {
            get {
                return ResourceManager.GetString("ConnectionStringConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many connection strings in config file..
        /// </summary>
        internal static string ConnectionStringConfigToMany {
            get {
                return ResourceManager.GetString("ConnectionStringConfigToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection configure for :{0}.
        /// </summary>
        internal static string ConnectionStringNameInvalid {
            get {
                return ResourceManager.GetString("ConnectionStringNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configure connection string by config file..
        /// </summary>
        internal static string ConnectionStringNoConfigException {
            get {
                return ResourceManager.GetString("ConnectionStringNoConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectionString.ProviderName.
        /// </summary>
        internal static string ConnectionStringProviderNameError {
            get {
                return ResourceManager.GetString("ConnectionStringProviderNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct type &apos;{0}&apos; with all mapped includedMembers..
        /// </summary>
        internal static string ConstructTypeInvalid {
            get {
                return ResourceManager.GetString("ConstructTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cann&apos;t convert from &apos;{0}&apos; to db type..
        /// </summary>
        internal static string ConvertTypeInvalid {
            get {
                return ResourceManager.GetString("ConvertTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Could not find required attribute &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string CouldNotFindRequiredAttribute {
            get {
                return ResourceManager.GetString("CouldNotFindRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle in topological sort.
        /// </summary>
        internal static string CycleInvalid {
            get {
                return ResourceManager.GetString("CycleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration query not allowed for this langauge.
        /// </summary>
        internal static string DeclarationQueryInvalid {
            get {
                return ResourceManager.GetString("DeclarationQueryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; cannot be deferred due to its type..
        /// </summary>
        internal static string DeferInvalid {
            get {
                return ResourceManager.GetString("DeferInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate has too many arguments.
        /// </summary>
        internal static string DelegateToManyArguments {
            get {
                return ResourceManager.GetString("DelegateToManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disposable must implement IDisposable.
        /// </summary>
        internal static string DisposableInvalid {
            get {
                return ResourceManager.GetString("DisposableInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type &apos;{0}&apos; not configure mapping!.
        /// </summary>
        internal static string EntityORMappingNoConfig {
            get {
                return ResourceManager.GetString("EntityORMappingNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat register entity mapping for entity {0}.
        /// </summary>
        internal static string EntityRepeatRegister {
            get {
                return ResourceManager.GetString("EntityRepeatRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression of type &apos;{0}&apos; is not a sequence.
        /// </summary>
        internal static string ExpressionError {
            get {
                return ResourceManager.GetString("ExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function：.
        /// </summary>
        internal static string FuncionInvalid {
            get {
                return ResourceManager.GetString("FuncionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare two constructed types with different sets of members assigned..
        /// </summary>
        internal static string InvalidOperationCompareException {
            get {
                return ResourceManager.GetString("InvalidOperationCompareException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of {0}.
        /// </summary>
        internal static string LengthInvalid {
            get {
                return ResourceManager.GetString("LengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not exist.
        /// </summary>
        internal static string NoExist {
            get {
                return ResourceManager.GetString("NoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find query provider.
        /// </summary>
        internal static string NoExistQueryProvider {
            get {
                return ResourceManager.GetString("NoExistQueryProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-scalar projections cannot be translated to SQL.
        /// </summary>
        internal static string NoProjectionTranslateToSQL {
            get {
                return ResourceManager.GetString("NoProjectionTranslateToSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast elements from type &apos;{0}&apos; to type &apos;{1}&apos;.
        /// </summary>
        internal static string NotCastFromTypeToType {
            get {
                return ResourceManager.GetString("NotCastFromTypeToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported {1}.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not support &apos;{1}&apos; operation {2}.
        /// </summary>
        internal static string OperationNotSupported {
            get {
                return ResourceManager.GetString("OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;{0}&apos; value in member {1} when OR mapping.
        /// </summary>
        internal static string ORMappingMissValue {
            get {
                return ResourceManager.GetString("ORMappingMissValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Provider name not exists or invalid for {1}.
        /// </summary>
        internal static string ProviderNameForInvalid {
            get {
                return ResourceManager.GetString("ProviderNameForInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider name invalid.
        /// </summary>
        internal static string ProviderNameInvalid {
            get {
                return ResourceManager.GetString("ProviderNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLCE can only support Skip when it is immediately followed by Take.
        /// </summary>
        internal static string SQLCESupportSkip {
            get {
                return ResourceManager.GetString("SQLCESupportSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subquery does not originate with a member access.
        /// </summary>
        internal static string SubqueryInvalid {
            get {
                return ResourceManager.GetString("SubqueryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is valid type.
        /// </summary>
        internal static string TypeInvalid {
            get {
                return ResourceManager.GetString("TypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled {0} type:{1}.
        /// </summary>
        internal static string TypeUnhandle {
            get {
                return ResourceManager.GetString("TypeUnhandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializer must be assignable to variable.
        /// </summary>
        internal static string VariableNoInitialize {
            get {
                return ResourceManager.GetString("VariableNoInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Version member type &apos;{0}&apos; for  &apos;{1}&apos; ,version type must be int type..
        /// </summary>
        internal static string VersionMemberTypeInvalid {
            get {
                return ResourceManager.GetString("VersionMemberTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version member too many in entity &apos;{0}&apos;.
        /// </summary>
        internal static string VersionTooMany {
            get {
                return ResourceManager.GetString("VersionTooMany", resourceCulture);
            }
        }
    }
}
